build:
  version: 1.9.4.7_2

accounts:
  message: "Welcome to Eazybank accounts related prod APIs"
  contactDetails:
    name: "Sanji Vinsmoke"
    email: "sanji@chefking.com"
  onCallSupport:
    - (123)456789
    - (987)654321