build:
  info: 2.45.3

cards:
  message: "Welcome to Eazybank cards related prod APIs"
  contactDetails:
    name: "Robin"
    email: "robin@archaeologist.com"
  onCallSupport:
    - (123)456789
    - (987)654321