build:
  info: 2.9.4

cards:
  message: "Welcome to Eazybank cards related qa APIs"
  contactDetails:
    name: "Nami"
    email: "nami@navigator.com"
  onCallSupport:
    - (123)456789
    - (987)654321